### ISSUE TITLE
tv problem

### ISSUE THREAD

**Issue by kenneth1516** [PickleModifications/ptelevision#2]
What ever is played on one tv plays on the other ones!

**Comment by anes66** [comment]
can confirm the same problem i think on all tv itd play the same

**Comment by PickleModifications** [comment]
Use Version 1.2+

**Comment by anes66** [comment]
i have also the latest version but same problem

**Comment by kenneth1516** [comment]
yeah still playing on all tvs

**Comment by PickleModifications** [comment]
Fixed on version v1.2.0.

**Comment by FelixDE** [comment]
Unfortunately the problem isn't fixed yet. If you turn on something on one TV and then go to others that haven't been used before, the same thing happens there.
